--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg130+1)
-- Dumped by pg_dump version 16.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: citext; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS citext WITH SCHEMA public;


--
-- Name: EXTENSION citext; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION citext IS 'data type for case-insensitive character strings';


--
-- Name: unaccent; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;


--
-- Name: EXTENSION unaccent; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION unaccent IS 'text search dictionary that removes accents';


--
-- Name: articles_rss_set_hash(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.articles_rss_set_hash() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.unique_hash := md5(
        COALESCE(NEW.titre, '') ||
        COALESCE(NEW.lien, '') ||
        COALESCE(NEW.published_at::text, '')
    );
    RETURN NEW;
END;
$$;


--
-- Name: company_aliases_norm_trg(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.company_aliases_norm_trg() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.alias_norm := lower(NEW.alias);
    RETURN NEW;
END;
$$;


--
-- Name: sector_aliases_norm_trg(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.sector_aliases_norm_trg() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    NEW.alias_norm := lower(NEW.alias);
    RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article_companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_companies (
    article_id integer NOT NULL,
    company_id integer NOT NULL,
    nbocc integer DEFAULT 0 NOT NULL,
    note_tfidf integer DEFAULT 0 NOT NULL,
    note_full integer DEFAULT 0 NOT NULL,
    date_estim date DEFAULT '1900-01-01'::date NOT NULL,
    note_targeted integer DEFAULT 0 NOT NULL,
    note_llama3 integer DEFAULT 0 NOT NULL,
    note_mistral integer DEFAULT 0 NOT NULL,
    note_queen integer DEFAULT 0 NOT NULL,
    note_gemini integer DEFAULT 0 NOT NULL,
    justification_lama text,
    justification_mistral text,
    justification_queen text,
    justification_gemini text,
    note_haiku integer DEFAULT 0 NOT NULL,
    justification_haiku text,
    statut_gemini character varying(20) DEFAULT 'not_evaluated'::character varying,
    statut_haiku character varying(20) DEFAULT 'not_evaluated'::character varying,
    statut_lama character varying(20) DEFAULT 'not_evaluated'::character varying,
    statut_mistral character varying(20) DEFAULT 'not_evaluated'::character varying,
    statut_queen character varying(20) DEFAULT 'not_evaluated'::character varying,
    prompt_version_gemini character varying(10),
    prompt_version_haiku character varying(10),
    prompt_version_lama character varying(10),
    prompt_version_mistral character varying(10),
    prompt_version_queen character varying(10)
);


--
-- Name: TABLE article_companies; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.article_companies IS 'Relation N–N entre articles et entreprises';


--
-- Name: article_sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.article_sectors (
    article_id integer NOT NULL,
    sector_id integer NOT NULL
);


--
-- Name: TABLE article_sectors; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.article_sectors IS 'Relation N–N entre articles et secteurs';


--
-- Name: articles_rss; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles_rss (
    id integer NOT NULL,
    titre text,
    lien text,
    date date,
    source text,
    contenu text,
    feed_id integer,
    published_at date,
    unique_hash character(32),
    companies_tagged_at timestamp with time zone,
    tagging_rules_version integer
);


--
-- Name: articles_rss_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles_rss ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_rss_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: companies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.companies (
    id integer NOT NULL,
    name text NOT NULL,
    isin text,
    ticker text,
    country text,
    sector_id integer
);


--
-- Name: compagnies_par_article; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.compagnies_par_article AS
 SELECT rss.id,
    com.name,
    ac.nbocc,
    ac.note_tfidf,
    ac.note_targeted,
    ac.note_full,
    ac.date_estim,
    rss.titre,
    rss.lien,
    rss.date
   FROM ((public.articles_rss rss
     LEFT JOIN public.article_companies ac ON ((rss.id = ac.article_id)))
     LEFT JOIN public.companies com ON ((ac.company_id = com.id)))
  ORDER BY rss.id, ac.article_id;


--
-- Name: companies_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.companies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: companies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.companies_id_seq OWNED BY public.companies.id;


--
-- Name: company_aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_aliases (
    id integer NOT NULL,
    company_id integer NOT NULL,
    alias public.citext NOT NULL,
    alias_norm text
);


--
-- Name: company_aliases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.company_aliases_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: company_aliases_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.company_aliases_id_seq OWNED BY public.company_aliases.id;


--
-- Name: notes_par_article; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.notes_par_article AS
 SELECT article_companies.article_id,
    article_companies.company_id,
    article_companies.nbocc,
    article_companies.note_llama3,
    article_companies.note_mistral,
    article_companies.note_queen,
    article_companies.note_gemini,
    article_companies.note_haiku,
    article_companies.statut_gemini,
    article_companies.statut_haiku,
    article_companies.statut_lama,
    article_companies.statut_mistral,
    article_companies.statut_queen,
    article_companies.justification_lama,
    article_companies.justification_mistral,
    article_companies.justification_queen,
    article_companies.justification_gemini,
    article_companies.justification_haiku,
    article_companies.prompt_version_gemini,
    article_companies.prompt_version_haiku,
    article_companies.prompt_version_lama,
    article_companies.prompt_version_mistral,
    article_companies.prompt_version_queen
   FROM public.article_companies
  WHERE ((article_companies.statut_gemini)::text = 'ok'::text)
  ORDER BY article_companies.article_id DESC, article_companies.company_id;


--
-- Name: rss_feeds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rss_feeds (
    id integer NOT NULL,
    name text NOT NULL,
    url text NOT NULL,
    source_domain text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    etag text,
    last_modified text,
    last_fetched_at timestamp with time zone
);


--
-- Name: rss_feeds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.rss_feeds_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: rss_feeds_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.rss_feeds_id_seq OWNED BY public.rss_feeds.id;


--
-- Name: sectors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sectors (
    id integer NOT NULL,
    name text NOT NULL
);


--
-- Name: secteurs_par_article; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.secteurs_par_article AS
 SELECT rss.id,
    sec.name,
    rss.titre,
    rss.lien,
    rss.date
   FROM ((public.articles_rss rss
     LEFT JOIN public.article_sectors asec ON ((rss.id = asec.article_id)))
     LEFT JOIN public.sectors sec ON ((asec.sector_id = sec.id)))
  ORDER BY rss.id, asec.sector_id;


--
-- Name: sector_aliases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sector_aliases (
    id integer NOT NULL,
    sector_id integer NOT NULL,
    alias public.citext NOT NULL,
    alias_norm text
);


--
-- Name: sector_aliases_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sector_aliases_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sector_aliases_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sector_aliases_id_seq OWNED BY public.sector_aliases.id;


--
-- Name: sectors_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sectors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sectors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sectors_id_seq OWNED BY public.sectors.id;


--
-- Name: companies id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies ALTER COLUMN id SET DEFAULT nextval('public.companies_id_seq'::regclass);


--
-- Name: company_aliases id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_aliases ALTER COLUMN id SET DEFAULT nextval('public.company_aliases_id_seq'::regclass);


--
-- Name: rss_feeds id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rss_feeds ALTER COLUMN id SET DEFAULT nextval('public.rss_feeds_id_seq'::regclass);


--
-- Name: sector_aliases id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector_aliases ALTER COLUMN id SET DEFAULT nextval('public.sector_aliases_id_seq'::regclass);


--
-- Name: sectors id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sectors ALTER COLUMN id SET DEFAULT nextval('public.sectors_id_seq'::regclass);


--
-- Name: article_companies article_companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_companies
    ADD CONSTRAINT article_companies_pkey PRIMARY KEY (article_id, company_id);


--
-- Name: article_sectors article_sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_sectors
    ADD CONSTRAINT article_sectors_pkey PRIMARY KEY (article_id, sector_id);


--
-- Name: articles_rss articles_rss_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles_rss
    ADD CONSTRAINT articles_rss_pkey PRIMARY KEY (id);


--
-- Name: articles_rss articles_rss_unique_hash_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles_rss
    ADD CONSTRAINT articles_rss_unique_hash_uk UNIQUE (unique_hash);


--
-- Name: companies companies_isin_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_isin_key UNIQUE (isin);


--
-- Name: companies companies_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_name_key UNIQUE (name);


--
-- Name: companies companies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_pkey PRIMARY KEY (id);


--
-- Name: company_aliases company_aliases_company_id_alias_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_aliases
    ADD CONSTRAINT company_aliases_company_id_alias_key UNIQUE (company_id, alias);


--
-- Name: company_aliases company_aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_aliases
    ADD CONSTRAINT company_aliases_pkey PRIMARY KEY (id);


--
-- Name: rss_feeds rss_feeds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rss_feeds
    ADD CONSTRAINT rss_feeds_pkey PRIMARY KEY (id);


--
-- Name: rss_feeds rss_feeds_url_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rss_feeds
    ADD CONSTRAINT rss_feeds_url_key UNIQUE (url);


--
-- Name: sector_aliases sector_aliases_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector_aliases
    ADD CONSTRAINT sector_aliases_pkey PRIMARY KEY (id);


--
-- Name: sector_aliases sector_aliases_sector_id_alias_uk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector_aliases
    ADD CONSTRAINT sector_aliases_sector_id_alias_uk UNIQUE (sector_id, alias);


--
-- Name: sectors sectors_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_name_key UNIQUE (name);


--
-- Name: sectors sectors_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sectors
    ADD CONSTRAINT sectors_pkey PRIMARY KEY (id);


--
-- Name: idx_article_companies_article_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_companies_article_id ON public.article_companies USING btree (article_id);


--
-- Name: idx_article_companies_company_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_companies_company_id ON public.article_companies USING btree (company_id);


--
-- Name: idx_article_sectors_article_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_sectors_article_id ON public.article_sectors USING btree (article_id);


--
-- Name: idx_article_sectors_sector_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_article_sectors_sector_id ON public.article_sectors USING btree (sector_id);


--
-- Name: idx_articles_rss_companies_tagged_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_articles_rss_companies_tagged_at ON public.articles_rss USING btree (companies_tagged_at);


--
-- Name: idx_articles_rss_fts; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_articles_rss_fts ON public.articles_rss USING gin (to_tsvector('french'::regconfig, ((COALESCE(titre, ''::text) || ' '::text) || COALESCE(contenu, ''::text))));


--
-- Name: idx_articles_rss_published_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_articles_rss_published_at ON public.articles_rss USING btree (published_at);


--
-- Name: idx_articles_rss_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_articles_rss_source ON public.articles_rss USING btree (source);


--
-- Name: idx_company_aliases_company_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_company_aliases_company_id ON public.company_aliases USING btree (company_id);


--
-- Name: idx_sector_aliases_sector_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sector_aliases_sector_id ON public.sector_aliases USING btree (sector_id);


--
-- Name: uq_company_alias_norm; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_company_alias_norm ON public.company_aliases USING btree (company_id, alias_norm);


--
-- Name: uq_sector_alias_norm; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_sector_alias_norm ON public.sector_aliases USING btree (sector_id, alias_norm);


--
-- Name: articles_rss trg_articles_rss_set_hash; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_articles_rss_set_hash BEFORE INSERT OR UPDATE OF titre, lien, date, published_at ON public.articles_rss FOR EACH ROW EXECUTE FUNCTION public.articles_rss_set_hash();


--
-- Name: company_aliases trg_company_aliases_norm; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_company_aliases_norm BEFORE INSERT OR UPDATE OF alias ON public.company_aliases FOR EACH ROW EXECUTE FUNCTION public.company_aliases_norm_trg();


--
-- Name: sector_aliases trg_sector_aliases_norm; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_sector_aliases_norm BEFORE INSERT OR UPDATE OF alias ON public.sector_aliases FOR EACH ROW EXECUTE FUNCTION public.sector_aliases_norm_trg();


--
-- Name: article_companies article_companies_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_companies
    ADD CONSTRAINT article_companies_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles_rss(id) ON DELETE CASCADE;


--
-- Name: article_companies article_companies_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_companies
    ADD CONSTRAINT article_companies_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;


--
-- Name: article_sectors article_sectors_article_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_sectors
    ADD CONSTRAINT article_sectors_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.articles_rss(id) ON DELETE CASCADE;


--
-- Name: article_sectors article_sectors_sector_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.article_sectors
    ADD CONSTRAINT article_sectors_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.sectors(id) ON DELETE CASCADE;


--
-- Name: articles_rss articles_rss_feed_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles_rss
    ADD CONSTRAINT articles_rss_feed_id_fkey FOREIGN KEY (feed_id) REFERENCES public.rss_feeds(id) ON DELETE SET NULL;


--
-- Name: companies companies_sector_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.companies
    ADD CONSTRAINT companies_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.sectors(id) ON DELETE SET NULL;


--
-- Name: company_aliases company_aliases_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_aliases
    ADD CONSTRAINT company_aliases_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id) ON DELETE CASCADE;


--
-- Name: sector_aliases sector_aliases_sector_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sector_aliases
    ADD CONSTRAINT sector_aliases_sector_id_fkey FOREIGN KEY (sector_id) REFERENCES public.sectors(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

